services:

  frontend:
    image: ghcr.io/ivash1228/gym-tracker-ui:latest
    container_name: front
    platform: linux/amd64
    ports:
      - "5174:80"
    depends_on:
      backend:
        condition: service_healthy

  backend:
    image: ghcr.io/ivash1228/gym-tracker:latest
    container_name: back
    platform: linux/amd64
    ports:
      - "8080:8080"